### ISSUE TITLE
Errors on windows

### ISSUE THREAD

**Issue by sonicviz** [bySabi/neal-sample-meteor#2]
Hi,
Looks like a neat project, but I get errors trying to run it.
I followed the recommended instructions to "Back to React 0.14.x" and "Back to builtin meteor jQuery 1.11.2" and updated meteor and all packages but still getting webpack errors as below:

[I removed and reinstalled webpack in case that was the issue, but apparently not]

G:\Meteor Projects\Project X\neal-sample-meteor-master>npm install webpack
neal-sample-meteor@1.0.0 G:\Meteor Projects\Project X\neal-sample-meteor-master
+-- css-loader@0.23.1
| `-- postcss@5.2.0
|`-- supports-color@3.1.2
+-- UNMET PEER DEPENDENCY react@15.3.1
+-- UNMET PEER DEPENDENCY react-dom@15.3.1
`-- webpack@1.13.2
  +-- acorn@3.3.0
  +-- enhanced-resolve@0.9.1
  |`-- memory-fs@0.2.0
  +-- interpret@0.6.6
  +-- memory-fs@0.3.0
  | `-- errno@0.1.4
  |`-- prr@0.0.0
  +-- node-libs-browser@0.6.0
  | +-- assert@1.4.1
  | +-- browserify-zlib@0.1.4
  | | `-- pako@0.2.9
  | +-- buffer@4.9.1
  | | +-- base64-js@1.1.2
  | |`-- ieee754@1.1.6
  | +-- console-browserify@1.1.0
  | | `-- date-now@0.1.4
  | +-- constants-browserify@0.0.1
  | +-- crypto-browserify@3.2.8
  | | +-- pbkdf2-compat@2.0.1
  | | +-- ripemd160@0.2.0
  | |`-- sha.js@2.2.6
  | +-- domain-browser@1.1.7
  | +-- events@1.1.1
  | +-- http-browserify@1.7.0
  | | `-- Base64@0.2.1
  | +-- https-browserify@0.0.0
  | +-- os-browserify@0.1.2
  | +-- path-browserify@0.0.0
  | +-- process@0.11.9
  | +-- punycode@1.4.1
  | +-- querystring-es3@0.2.1
  | +-- readable-stream@1.1.14
  | |`-- isarray@0.0.1
  | +-- stream-browserify@1.0.0
  | | `-- readable-stream@1.1.14
  | |`-- isarray@0.0.1
  | +-- timers-browserify@1.4.2
  | | `-- process@0.11.9
  | +-- tty-browserify@0.0.0
  | +-- url@0.10.3
  | |`-- punycode@1.3.2
  | +-- util@0.10.3
  | | `-- inherits@2.0.1
  |`-- vm-browserify@0.0.4
  |   `-- indexof@0.0.1
  +-- optimist@0.6.1
  | +-- minimist@0.0.10
  |`-- wordwrap@0.0.3
  +-- supports-color@3.1.2
  +-- tapable@0.1.10
  +-- uglify-js@2.6.4
  | +-- async@0.2.10
  | +-- uglify-to-browserify@1.0.2
  | `-- yargs@3.10.0
  |   +-- camelcase@1.2.1
  |   +-- cliui@2.1.0
  |   | +-- center-align@0.1.3
  |   | | +-- align-text@0.1.4
  |   | | | +-- longest@1.0.1
  |   | | |`-- repeat-string@1.5.4
  |   | | `-- lazy-cache@1.0.4
  |   | +-- right-align@0.1.3
  |   |`-- wordwrap@0.0.2
  |   `-- window-size@0.1.0
  +-- watchpack@0.2.9
  | +-- async@0.9.2
  |`-- chokidar@1.6.0
  |   +-- anymatch@1.3.0
  |   | +-- arrify@1.0.1
  |   | `-- micromatch@2.3.11
  |   |   +-- arr-diff@2.0.0
  |   |   |`-- arr-flatten@1.0.1
  |   |   +-- array-unique@0.2.1
  |   |   +-- braces@1.8.5
  |   |   | +-- expand-range@1.8.2
  |   |   | | `-- fill-range@2.2.3
  |   |   | |   +-- is-number@2.1.0
  |   |   | |   +-- isobject@2.1.0
  |   |   | |`-- randomatic@1.1.5
  |   |   | +-- preserve@0.2.0
  |   |   | `-- repeat-element@1.1.2
  |   |   +-- expand-brackets@0.1.5
  |   |   |`-- is-posix-bracket@0.1.1
  |   |   +-- extglob@0.3.2
  |   |   +-- filename-regex@2.0.0
  |   |   +-- kind-of@3.0.4
  |   |   | `-- is-buffer@1.1.4
  |   |   +-- normalize-path@2.0.1
  |   |   +-- object.omit@2.0.0
  |   |   | +-- for-own@0.1.4
  |   |   | |`-- for-in@0.1.5
  |   |   | `-- is-extendable@0.1.1
  |   |   +-- parse-glob@3.0.4
  |   |   | +-- glob-base@0.3.0
  |   |   |`-- is-dotfile@1.0.2
  |   |   `-- regex-cache@0.4.3
  |   |     +-- is-equal-shallow@0.1.3
  |   |`-- is-primitive@2.0.0
  |   +-- async-each@1.0.1
  |   +-- glob-parent@2.0.0
  |   +-- is-binary-path@1.0.1
  |   | `-- binary-extensions@1.6.0
  |   +-- is-glob@2.0.1
  |   |`-- is-extglob@1.0.0
  |   `-- readdirp@2.1.0
  |`-- set-immediate-shim@1.0.1
  `-- webpack-core@0.6.8
`-- source-map@0.4.4

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN react-waypoint@1.3.1 requires a peer of react@^0.14.0 but none was installed.
npm WARN react-waypoint@1.3.1 requires a peer of react-dom@^0.14.0 but none was installed.
npm WARN neal-sample-meteor@1.0.0 No license field.

G:\Meteor Projects\Project X\neal-sample-meteor-master>meteor
[[[[[ ~\G\Meteor Projects\Project X\neal-sample-meteor-master ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While processing files with webpack:webpack (for target web.browser):
   plugin/WebpackCompiler.js:824:10: fs.existsSync is not a function
   at checkMigration (plugin/WebpackCompiler.js:824:10)
   at WebpackCompiler.processFilesForTarget (plugin/WebpackCompiler.js:46:5)

   While processing files with webpack:webpack (for target os.windows.x86_32):
   plugin/WebpackCompiler.js:824:10: fs.existsSync is not a function
   at checkMigration (plugin/WebpackCompiler.js:824:10)
   at WebpackCompiler.processFilesForTarget (plugin/WebpackCompiler.js:46:5)

=> Your application has errors. Waiting for file change.

**Comment by bySabi** [comment]
It is related to https://github.com/sass/node-sass/issues/1515

I never build this project on windows but definitly it need a meteor 1.4/node 4 upgrade.

PR are welcome.

I will look it when I have some free time
